portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('admin/', admin.site.urls),
]

projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.all_projects, name="all_projects"),
    path('<int:pk>', views.project_detail, name="detail"),
]

projects/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.CharField(max_length=100)

    def __str__(self):
        return self.title

projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project

# Create your views here.


def all_projects(request):
    projects = Project.objects.all()
    return render(request, 'projects/all_projects.html', {'projects': projects})


def project_detail(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request, 'projects/detail.html',
                  {'project': project})

projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}


    <h1>Projects</h1>
    <div class="row">
    {% for project in projects %}
        <div class="col-md-4">
            <div class="card mb-2">
                <img class="card-img-top" src="{% static project.image %}" alt="screenshot of project"">
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <p class="card-text">{{ project.description }}</p>
                    <a href="{% url 'projects:detail' project.pk %}"
                    class="btn btn-primary">
                        Read More
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>


{% endblock %}

projects/templates/projects/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <title>Portfolio</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-secondary ">
      <a class="navbar-brand" href="{% url 'projects:all_projects' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'projects:all_projects' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projects:all_projects' %}">Features</a>
          </li>
        </ul>
      </div>
    </nav>


    <div class="container">
    {% block content %}

    {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>{{project.title}}</h1>
    <div class="row">
        <div class="col-md-8">
            <img class="card-img-top" src="{% static project.image %}" alt="{{ project.description }}"/>
        </div>
        <div class="col-md-4">
            <h5>About the project</h5>
            <p>{{project.description}}</p>
            <h5>Built with:</h5>
            <p>{{ project.technology }}</p>
        </div>
    </div>
</div>

{% endblock %}